import AppKit
import Foundation

enum PasteboardTypes {
    static let clipwordMarker = NSPasteboard.PasteboardType("com.clipword.app.marker")

    static let defaultIgnoredTypes: [String] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    ]
}

struct PasteboardSnapshot: Codable {
    var plainText: String?
    var rtfData: Data?
    var htmlData: Data?
    var imageData: Data?
    var fileURLs: [String]?
    var contentType: ContentType
    var pasteboardTypes: [String]?
    var hasColorOnPasteboard: Bool?

    static func capture(from pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        let types = pasteboard.types?.map(\.rawValue) ?? []
        let hasColor = NSPasteboard.PasteboardType.color.isAvailable(on: pasteboard)

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !urls.isEmpty,
           urls.allSatisfy({ $0.isFileURL }) {
            return PasteboardSnapshot(
                plainText: urls.map(\.path).joined(separator: "\n"),
                fileURLs: urls.map(\.absoluteString),
                contentType: .file,
                pasteboardTypes: types,
                hasColorOnPasteboard: hasColor
            )
        }

        if types.contains("public.url") || types.contains(where: { $0.hasSuffix(".url") }) {
            let urlString = pasteboard.string(forType: .URL)
                ?? pasteboard.string(forType: NSPasteboard.PasteboardType("public.url"))
                ?? pasteboard.string(forType: .string)
            if let urlString, !urlString.isEmpty {
                return PasteboardSnapshot(
                    plainText: urlString,
                    contentType: .text,
                    pasteboardTypes: types,
                    hasColorOnPasteboard: hasColor
                )
            }
        }

        if let image = NSImage(pasteboard: pasteboard),
           let tiff = image.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return PasteboardSnapshot(
                plainText: "Image (\(Int(image.size.width))×\(Int(image.size.height)))",
                imageData: png,
                contentType: .image,
                pasteboardTypes: types,
                hasColorOnPasteboard: hasColor
            )
        }

        if let html = pasteboard.string(forType: .html) {
            return PasteboardSnapshot(
                plainText: pasteboard.string(forType: .string) ?? html,
                htmlData: html.data(using: .utf8),
                contentType: .html,
                pasteboardTypes: types,
                hasColorOnPasteboard: hasColor
            )
        }

        if let rtf = pasteboard.data(forType: .rtf) {
            let plain = pasteboard.string(forType: .string)
            return PasteboardSnapshot(
                plainText: plain,
                rtfData: rtf,
                contentType: .rtf,
                pasteboardTypes: types,
                hasColorOnPasteboard: hasColor
            )
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            return PasteboardSnapshot(
                plainText: text,
                contentType: .text,
                pasteboardTypes: types,
                hasColorOnPasteboard: hasColor
            )
        }

        return nil
    }

    func encode() -> Data? {
        try? JSONEncoder().encode(self)
    }

    static func decode(from data: Data) -> PasteboardSnapshot? {
        try? JSONDecoder().decode(PasteboardSnapshot.self, from: data)
    }

    func write(to pasteboard: NSPasteboard, withoutFormatting: Bool) {
        pasteboard.clearContents()
        if withoutFormatting, let plainText {
            pasteboard.setString(plainText, forType: .string)
            if let fileURLs {
                let urls = fileURLs.compactMap { URL(string: $0) }
                pasteboard.writeObjects(urls as [NSURL])
            }
            return
        }

        switch contentType {
        case .file:
            if let fileURLs {
                let urls = fileURLs.compactMap { URL(string: $0) }
                pasteboard.writeObjects(urls as [NSURL])
            }
        case .image:
            if let imageData, let image = NSImage(data: imageData) {
                pasteboard.writeObjects([image])
            }
        case .html:
            if let htmlData, let html = String(data: htmlData, encoding: .utf8) {
                pasteboard.setString(html, forType: .html)
            }
            if let plainText { pasteboard.setString(plainText, forType: .string) }
        case .rtf:
            if let rtfData { pasteboard.setData(rtfData, forType: .rtf) }
            if let plainText { pasteboard.setString(plainText, forType: .string) }
        case .text:
            if let plainText { pasteboard.setString(plainText, forType: .string) }
        }
        pasteboard.setString("clipword", forType: PasteboardTypes.clipwordMarker)
    }
}

private extension NSPasteboard.PasteboardType {
    func isAvailable(on pasteboard: NSPasteboard) -> Bool {
        pasteboard.types?.contains(self) ?? false
    }
}
